'use client';

import { useState, useEffect } from 'react';

interface QRCodeDisplayProps {
  attendeeName: string;
  registrationId: string;
  eventId: string;
}

export function QRCodeDisplay({ attendeeName, registrationId, eventId }: QRCodeDisplayProps) {
  const [qrCodeData, setQrCodeData] = useState<string>('');
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Simulate QR code generation
    const generateQRCode = async () => {
      setIsLoading(true);
      
      // Simulate API call to generate QR code
      await new Promise(resolve => setTimeout(resolve, 1000));
      
      // Create dummy QR code data (in real app, this would be generated by backend)
      const qrData = JSON.stringify({
        registrationId,
        eventId,
        attendeeName,
        timestamp: Date.now(),
        checkInCode: `CHK-${registrationId.slice(-8).toUpperCase()}`
      });
      
      // For demo purposes, we'll create a simple SVG QR code placeholder
      const qrCodeSvg = generateQRCodeSVG(qrData);
      setQrCodeData(qrCodeSvg);
      setIsLoading(false);
    };

    generateQRCode();
  }, [attendeeName, registrationId, eventId]);

  // Simple QR code SVG generator (placeholder for real QR code library)
  const generateQRCodeSVG = (data: string) => {
    const size = 200;
    const modules = 25; // 25x25 grid for simplicity
    const moduleSize = size / modules;
    
    // Create a simple pattern based on the data hash
    const hash = data.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    let pattern = '';
    
    for (let y = 0; y < modules; y++) {
      for (let x = 0; x < modules; x++) {
        // Create pseudo-random pattern based on position and hash
        const shouldFill = ((x + y + hash) % 3) === 0 || 
                          (x < 7 && y < 7) || // Top-left finder pattern
                          (x >= modules - 7 && y < 7) || // Top-right finder pattern
                          (x < 7 && y >= modules - 7); // Bottom-left finder pattern
        
        if (shouldFill) {
          pattern += `<rect x="${x * moduleSize}" y="${y * moduleSize}" width="${moduleSize}" height="${moduleSize}" fill="black"/>`;
        }
      }
    }
    
    return `
      <svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg">
        <rect width="${size}" height="${size}" fill="white"/>
        ${pattern}
      </svg>
    `;
  };

  const downloadQRCode = () => {
    const blob = new Blob([qrCodeData], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `qr-code-${attendeeName.replace(/\s+/g, '-').toLowerCase()}.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="premium-glass rounded-3xl p-8 text-center">
      <h3 className="text-xl md:text-2xl font-light mb-6 premium-text-gradient">
        Your Check-in QR Code
      </h3>
      
      {isLoading ? (
        <div className="flex flex-col items-center space-y-4">
          <div className="w-48 h-48 bg-black/50 border border-amber-500/30 rounded-2xl flex items-center justify-center">
            <div className="w-8 h-8 border-2 border-amber-500/30 border-t-amber-500 rounded-full animate-spin"></div>
          </div>
          <p className="text-gray-400">Generating your QR code...</p>
        </div>
      ) : (
        <div className="flex flex-col items-center space-y-6">
          {/* QR Code Display */}
          <div className="bg-white p-6 rounded-2xl shadow-2xl">
            <div 
              dangerouslySetInnerHTML={{ __html: qrCodeData }}
              className="w-48 h-48"
            />
          </div>
          
          {/* Instructions */}
          <div className="space-y-3 text-gray-300">
            <p className="font-medium">Present this QR code at the event for check-in</p>
            <p className="text-sm">
              Save this code to your phone or print it out. You can also find it in your confirmation email.
            </p>
          </div>
          
          {/* Actions */}
          <div className="flex flex-col sm:flex-row gap-3">
            <button
              onClick={downloadQRCode}
              className="premium-button bg-gradient-to-r from-amber-500 via-amber-600 to-amber-500 hover:from-amber-400 hover:via-amber-500 hover:to-amber-400 text-white px-6 py-3 rounded-full text-sm font-medium tracking-wide"
            >
              Download QR Code
            </button>
            <button
              onClick={() => {
                if (navigator.share) {
                  navigator.share({
                    title: 'My Event QR Code',
                    text: `QR Code for ${attendeeName} - LEM Ventures Launch`,
                    files: [new File([qrCodeData], 'qr-code.svg', { type: 'image/svg+xml' })]
                  });
                }
              }}
              className="text-amber-400 hover:text-amber-300 font-medium transition-colors duration-300 px-6 py-3"
            >
              Share QR Code
            </button>
          </div>
        </div>
      )}
    </div>
  );
}